import { useEffect, useState } from 'react'
import { ArrowUpRight, ArrowLeft, ArrowRight, ShoppingBag, Search, Minus, Plus, X } from 'lucide-react'
import { Button } from './components/ui/button'
import { Modal } from './components/ui/dialog'
import { ShoeStage } from './components/ShoeStage'
import { Checkout } from './components/Checkout'
import { products, money, photo } from './data/products'

function readCart() { try { const items=JSON.parse(localStorage.getItem('kicks-cart')||'[]'); return Array.isArray(items) ? items.filter(item=>products.some(p=>p.id===item.id)&&Number.isInteger(item.qty)&&item.qty>0) : [] } catch { return [] } }
function ProductPage({product,onAdd}) {
  const [size,setSize]=useState(null)
  const [image,setImage]=useState(product.image)
  const [error,setError]=useState('')
  return <main className="mx-auto max-w-[1500px] px-5 py-8 md:px-12"><a href="#shop" className="mb-8 inline-flex items-center gap-2 text-sm"><ArrowLeft size={16}/> Back to the collection</a><div className="grid gap-8 lg:grid-cols-[1.35fr_1fr] lg:gap-16"><div><ShoeStage key={image} image={image} name={`${product.brand} ${product.name}`}/>{product.gallery && <div className="mt-4 flex gap-3">{product.gallery.map((src,index)=><button key={src} onClick={()=>setImage(src)} aria-label={`View ${product.name} photo ${index+1}`} aria-pressed={src===image} className={`size-20 bg-muted p-2 ${src===image?'ring-2 ring-primary':''}`}><img src={photo(src)} alt="" className="size-full object-contain"/></button>)}</div>}</div><div className="py-2 lg:py-12"><p className="mb-3 text-sm uppercase tracking-widest text-muted-foreground">{product.brand}</p><h1 className="text-5xl font-black tracking-tighter md:text-7xl">{product.name}</h1><p className="mt-4 text-muted-foreground">{product.color}</p><p className="mt-7 text-2xl font-semibold">{money(product.price)}</p><p className="mt-6 max-w-md leading-7 text-muted-foreground">{product.description}</p><fieldset className="mt-8"><legend className="mb-4 font-semibold">Choose your size <span className="ml-2 text-xs font-normal text-muted-foreground">EU sizing</span></legend><div className="grid grid-cols-4 gap-2">{product.sizes.map(value=><button key={value} onClick={()=>{setSize(value);setError('')}} aria-pressed={size===value} className={`min-h-12 border ${size===value?'border-foreground bg-foreground text-background':'border-border hover:border-foreground'}`}>{value}</button>)}</div></fieldset><p role="alert" className="mt-2 min-h-6 text-sm text-primary">{error}</p><Button className="w-full" onClick={()=>size ? onAdd(product,size) : setError('Choose a size before adding to your bag.')}>Add to bag <Plus/></Button><p className="mt-5 text-xs leading-5 text-muted-foreground">Demo catalog. Prices, sizes and product identities need seller confirmation before launch. Product photos have been edited.</p><details className="mt-8 border-t border-border py-4"><summary className="cursor-pointer font-semibold">Delivery & returns</summary><p className="mt-4 text-sm leading-6 text-muted-foreground">Delivery rates and returns terms will be confirmed before live checkout. No payment is collected in this preview.</p></details></div></div></main>
}
export default function App() {
  const [route,setRoute]=useState(location.hash)
  const [filter,setFilter]=useState('All pairs')
  const [query,setQuery]=useState('')
  const [sort,setSort]=useState('featured')
  const [cart,setCart]=useState(readCart)
  const [modal,setModal]=useState(null)
  useEffect(()=>{const change=()=>{setRoute(location.hash);if(location.hash.startsWith('#product/'))window.scrollTo(0,0)};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[])
  useEffect(()=>{try{localStorage.setItem('kicks-cart',JSON.stringify(cart))}catch{/* Shopping still works if storage is unavailable. */}},[cart])
  const items=cart.map(item=>({...products.find(p=>p.id===item.id),...item}))
  const total=items.reduce((sum,item)=>sum+item.price*item.qty,0)
  const count=items.reduce((sum,item)=>sum+item.qty,0)
  const current=products.find(p=>`#product/${p.id}`===route)
  const visible=products.filter(p=>(filter==='All pairs'||p.brand===filter||p.category===filter)&&`${p.brand} ${p.name} ${p.color}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0)
  const add=(product,size)=>{const key=`${product.id}-${size}`;setCart(old=>old.some(item=>item.key===key)?old.map(item=>item.key===key?{...item,qty:item.qty+1}:item):[...old,{id:product.id,size,key,qty:1}]);setModal('bag')}
  const quantity=(key,amount)=>setCart(old=>old.map(item=>item.key===key?{...item,qty:item.qty+amount}:item).filter(item=>item.qty>0))
  const shop=(category)=>{setFilter(category);location.hash='shop';setTimeout(()=>document.getElementById('shop')?.scrollIntoView(),0)}
  return <>
    <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-background focus:p-4">Skip to content</a>
    <header className="mx-auto flex h-20 max-w-[1500px] items-center justify-between gap-4 px-5 md:px-12"><a href="#" aria-label="Kicks home" className="text-4xl font-black italic tracking-tighter">kicks<span className="text-primary">.</span></a><nav className="hidden gap-8 text-sm font-medium md:flex"><a href="#shop" onClick={()=>setFilter('All pairs')}>Shop all</a><button onClick={()=>shop('Lifestyle')}>Lifestyle</button><button onClick={()=>shop('Court')}>Court</button><button onClick={()=>shop('Sport style')}>Sport style</button></nav><Button variant="outline" onClick={()=>setModal('bag')} aria-label={`Open bag, ${count} items`}><ShoppingBag/> Bag ({count})</Button></header>
    <div id="main">{current ? <ProductPage key={current.id} product={current} onAdd={add}/> : <main>
      <section className="relative mx-3 grid overflow-hidden rounded-2xl bg-primary text-primary-foreground md:mx-6 lg:min-h-[640px] lg:grid-cols-2"><div className="relative z-10 px-7 pt-14 pb-8 md:px-12 lg:py-24"><p className="mb-6 text-sm font-semibold uppercase tracking-[.2em]">For the everyday rotation</p><h1 className="max-w-xl text-6xl leading-[.95] font-black tracking-[-.065em] sm:text-8xl lg:text-[104px]">GOOD SOLES.<br/>GREAT DAYS.</h1><p className="mt-7 max-w-xs text-base leading-7">Court classics. Low-top favourites. Pairs with a little more personality.</p><Button asChild className="mt-8 bg-background text-foreground hover:bg-muted"><a href="#shop">Find your next pair <ArrowUpRight/></a></Button></div><a href="#product/samba-green" className="group relative flex min-h-[350px] items-center justify-center lg:min-h-full" aria-label="Explore green Adidas Samba"><span aria-hidden="true" className="absolute select-none text-[clamp(90px,15vw,220px)] font-black italic tracking-tighter text-primary-foreground/10">SAMBA</span><img src={photo('samba-green')} alt="Forest green Adidas Samba with cream stripes and a gum sole" fetchPriority="high" className="relative w-[90%] max-h-[590px] object-contain drop-shadow-2xl transition-transform duration-700 motion-safe:group-hover:-translate-y-5 motion-safe:group-hover:-rotate-6"/><span className="absolute right-6 bottom-6 flex size-14 items-center justify-center rounded-full border border-primary-foreground/50"><ArrowUpRight/></span></a></section>
      <section id="shop" className="mx-auto max-w-[1500px] px-5 py-16 md:px-12 md:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><h2 className="text-4xl font-black tracking-tighter md:text-6xl">YOUR NEXT ROTATION<span className="text-primary">.</span></h2><p className="text-sm text-muted-foreground">{visible.length} pairs to explore</p></div><div className="mt-8 flex flex-wrap items-center justify-between gap-5"><div className="flex flex-wrap gap-2">{['All pairs','Nike','Adidas','Puma','Sport style','Slip-ons'].map(name=><button key={name} aria-pressed={filter===name} onClick={()=>setFilter(name)} className={`min-h-11 rounded-full border px-5 text-sm ${filter===name?'border-foreground bg-foreground text-background':'border-border hover:border-foreground'}`}>{name}</button>)}</div><div className="flex w-full gap-2 sm:w-auto"><label className="relative flex-1"><Search className="absolute left-3 top-3" size={17}/><input aria-label="Search shoes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a pair" className="h-11 w-full rounded-full border border-border bg-transparent pl-10 pr-3 sm:w-44"/></label><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)} className="max-w-40 rounded-full border border-border bg-transparent px-3 text-sm"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div></div><p className="mt-5 text-xs text-muted-foreground">Demo collection. Prices and availability are illustrative.</p><div className="mt-8 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 xl:grid-cols-3">{visible.map(product=><article key={product.id}><a href={`#product/${product.id}`} className="group block"><div className="flex aspect-[4/3] items-center justify-center overflow-hidden rounded-xl bg-muted"><img src={photo(product.image)} alt={`${product.brand} ${product.name}, ${product.color}`} loading="lazy" className="h-[85%] w-[85%] object-contain transition-transform duration-500 motion-safe:group-hover:-translate-y-3 motion-safe:group-hover:-rotate-6"/></div><div className="mt-4 flex justify-between gap-3"><div><p className="mb-1 text-xs text-muted-foreground">{product.brand} / {product.category}</p><h3 className="text-xl font-bold tracking-tight">{product.name}</h3><p className="mt-1 text-sm text-muted-foreground">{product.color}</p></div><div className="text-right"><p className="text-sm font-semibold">{money(product.price)}</p><ArrowUpRight className="mt-4 ml-auto" size={20}/></div></div></a></article>)}</div>{visible.length===0&&<div className="py-20 text-center"><p className="mb-5">No pairs match your search.</p><Button onClick={()=>{setFilter('All pairs');setQuery('')}}>Reset filters</Button></div>}</section>
      <section className="mx-5 mb-16 flex flex-wrap items-center justify-between gap-6 rounded-2xl bg-muted p-8 md:mx-12 md:p-12"><h2 className="max-w-xl text-4xl font-black tracking-tighter md:text-6xl">FROM THE COURT.<br/>INTO YOUR EVERYDAY.</h2><Button onClick={()=>shop('Court')}>Explore court styles <ArrowUpRight/></Button></section>
    </main>}</div>
    <footer className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-6 border-t border-border px-5 py-10 md:px-12"><a href="#" className="text-5xl font-black italic tracking-tighter">kicks.</a><p className="text-sm text-muted-foreground">A fresh pair. A different pace.</p><span className="text-xs text-muted-foreground">© {new Date().getFullYear()} Kicks. Demo storefront.</span></footer>
    <Modal open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}} title={modal==='checkout'?'Your details':'Your bag'} description={modal==='checkout'?'Create a preview of your custom Kicks receipt.':`${count} ${count===1?'pair':'pairs'} in your rotation.`}>{modal==='checkout'?<Checkout items={items} onComplete={()=>setModal(null)}/>:items.length===0?<div className="py-10 text-center"><ShoppingBag className="mx-auto mb-4"/><p className="mb-6">Your next pair is out there.</p><Button onClick={()=>{setModal(null);shop('All pairs')}}>Explore the collection</Button></div>:<><div className="space-y-6">{items.map(item=><div key={item.key} className="flex gap-4"><img src={photo(item.image)} alt="" className="size-20 rounded-lg bg-muted object-contain p-2"/><div className="flex-1"><p className="font-bold">{item.name}</p><p className="text-xs text-muted-foreground">{item.color} / EU {item.size}</p><div className="mt-2 flex items-center gap-3"><button className="grid size-9 place-items-center rounded-full border border-border" onClick={()=>quantity(item.key,-1)} aria-label={`Decrease ${item.name} quantity`}><Minus size={14}/></button><span>{item.qty}</span><button className="grid size-9 place-items-center rounded-full border border-border" onClick={()=>quantity(item.key,1)} aria-label={`Increase ${item.name} quantity`}><Plus size={14}/></button></div></div><div className="text-right text-sm"><p>{money(item.price*item.qty)}</p><button className="mt-3 p-2" aria-label={`Remove ${item.name}`} onClick={()=>setCart(old=>old.filter(x=>x.key!==item.key))}><X size={16}/></button></div></div>)}</div><div className="mt-8 flex justify-between border-t border-border py-5 font-bold"><span>Subtotal</span><span>{money(total)}</span></div><Button className="w-full" onClick={()=>setModal('checkout')}>Continue to demo checkout <ArrowRight/></Button></>}</Modal>
  </>
}
